apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::132179812354:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-DAbqgXgVIfXN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::132179812354:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-24T06:26:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2924"
  uid: 5dc476ad-c797-45e9-b5a8-8ee69aee3618
