apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::116758249766:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-ZjPupcIsqb3s
      username: system:node:{{EC2PrivateDNSName}}
    - system:masters
      rolearn: arn:aws:iam::116758249766:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-23T08:42:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2806"
  uid: c371d415-fe12-4dea-a650-7649b9076b37
